### ISSUE TITLE
tag output inconsistent with usaddress

### ISSUE THREAD

**Issue by derekeder** [datamade/probablepeople#10]
```python
import probablepeople
probablepeople.tag('derek w eder')
> OrderedDict([('GivenName', 'derek'), ('MiddleInitial', 'w'), ('Surname', 'eder')])

import usaddress
usaddress.tag('123 main st')
> (OrderedDict([('AddressNumber', '123'), ('StreetName', 'main'), ('StreetNamePostType', 'st')]),
 'Street Address')
```

usaddress returns a tuple with an OrderedDict and another descriptive tag, where probablepeople does not. is this intentional?

**Comment by cathydeng** [comment]
ya, the tag method in usaddress returns an address type (e.g. street address, intersection, po box). I believe @fgregg added this to better compare address pairs.

@fgregg  - should we add something analogous for the tag method in probablepeople? I guess the formats would be single name, couple, or company if we end up adding company parsing?

**Comment by fgregg** [comment]
We could go ahead and add "person name" "couple names" now
