### ISSUE TITLE
name formats the parser could improve on, w/ additional training data

### ISSUE THREAD

**Issue by cathydeng** [datamade/probablepeople#12]
- [x] nicknames w/ multiple tokens
- [ ] political titles, like Senator/Congressman/Mayor
- [x] PACS

**Comment by stevevance** [comment]
I was analyzing Cook County property tax records and grouping by the name of the recipient, ordering by the number of times the name appears (in descending order). It's no surprise that a lot of corporations and organizations are the most frequent property tax bill recipients. 

I would like ````probablepeople```` to determine if the name is a person or an organization. Here are the  20 property tax bill recipients for residential condos in 2014:

TAXPAYER OF
GRANT PARK CHICAGO
235 VAN BUREN, CORP
RENAISSANCE RESIDENTAL
CHICAGO UNIVERSITY COM
TAX PAYER OF
1555 WABASH, LLC
SCENIC TREE, LLC
OPT OLD ORCHARD LLC
MONROE WABASH DEV
CURRENT OWNER
BROADVILLE CONDOS LLC
ONTARIO PLACE LLC
55 ERIE INVESTORS LLC
CATHERINE CTS. CONDO
PRESBYTERIAN HOMES
401 N. Wabash LLC
PARKSIDE OLD TOWN I
CHICAGO TITLE LAND TRU
PINE HILLS LLC

**Comment by fgregg** [comment]
It does already. Pull down the most recent version.

**Comment by stevevance** [comment]
@fgregg Okay, will do. I was using the website version last night.

**Comment by twneale** [comment]
I noticed that part of the issue in #8 seems to be caused by the nickname "The Pill" being tokenized as ('"The', 'Pill"'), which actually parses correctly if you remove the space or replace it with two words that are strongly jamey:

**Comment by fgregg** [comment]
hmm.. that's an interesting idea!

**Comment by fgregg** [comment]
Thinking about this more I think it would be better as a token feature. `Within-parenthetica:true`

**Comment by fgregg** [comment]
Hmm... actually, I think the main thing is that we don't have a lot of two name nicknames. @twneale we need a corpus of gangster names.

**Comment by twneale** [comment]
@fgregg or maybe pro athletes!
http://en.m.wikipedia.org/wiki/List_of_sportspeople_by_nickname

**Comment by fgregg** [comment]
Want to do a little parsing and turn that into a CSV? We'll take it from there.

**Comment by cathydeng** [comment]
hey @twneale - probablepeople 0.3.1 is now handling nicknames w/ multiple tokens pretty well. thanks!

**Comment by twneale** [comment]
:+1:  You rock, @cathydeng !
