### ISSUE TITLE
Misidentifying corporations as persons

### ISSUE THREAD

**Issue by stevevance** [datamade/probablepeople#15]
I parsed a list of the top 100 Cook County property tax bill recipients (by number of PINs they receive bills for). 

All persons – by my review – were identified correctly as Person, but the following 8 names were mistakenly identified as persons:

* 235 VAN BUREN
* BAFCO
* CURRENT TAXPAYER
* HOMEWERKS-LAMONT
* HUD
* NULL
* SCENIC TREE
* TAXPAYER

**Comment by cathydeng** [comment]
hey @stevevance - thx for trying it out!

I'll add BAFCO & HOMEWERKS-LAMONT to the training data as corporations, but for the other 6 strings, I'm not sure what the 'true' labels would even be. thoughts?

this library can parse name/household/corporation input strings, but doesn't verify whether a string is a name/household/corporation vs none of the three.

**Comment by stevevance** [comment]
@cathydeng I think "235 VAN BUREN" should be ruled out as a name because it has a number in it. The others, I don't know. Maybe "null" should be a reserved word?

**Comment by fgregg** [comment]
- HUD is a corporation
- Scenic Tree is probably a corporation

The scope of probablepeople is to parse names, not identify names. So

We won't handle

- Null, Not a name
- Taxpayer, Not a name
- 235 Van Buren (NB. there are a lot of businesses that are like "235 Van Buren, LLC")
