### ISSUE TITLE
Handle Clergy Prefixes

### ISSUE THREAD

**Issue by wiremine** [datamade/probablepeople#18]
The parser does not handle the "Rev." (short for Reverend) prefix correct: 

"Bob Smith" => [('Rev.', 'GivenName'), ('Bob', 'MiddleName'), ('Smith', 'Surname')]

"Rev. Bob & Susan Smith" => [('Rev.', 'And'), ('Bob', 'GivenName'), ('&', 'And'), ('Susan', 'GivenName'), ('Smith', 'Surname')]

"Rev. Bob & Susan Sugar" => [('Rev.', 'CorporationName'), ('Bob', 'CorporationName'), ('&', 'CorporationName'), ('Susan', 'CorporationName'), ('Sugar', 'CorporationName')]

I think "Rev." should be classified as a "PrefixOther"

**Comment by fgregg** [comment]
Do you happen to have a list of names like this that you could share?

**Comment by wiremine** [comment]
@fgregg I'd be happy to help, but I'm not sure exactly what you're looking for. Rev. is a fairly standard prefix (just like Mr. or Dr.). Are you looking for names of Reverends?

**Comment by fgregg** [comment]
We like to train the model with real data, to the extent possible. Looking
for a lists of names with this prefix.

**Comment by wiremine** [comment]
Here are some famous Reverends:

Rev. Billy Graham
Rev. Martin Luther King. Jr.
Rev. Dietrich Bonhoeffer
Rev. Rick Warren 
Rev. Dwight Moody
Rev. Charles Spurgeon
Rev. Charles Stanley
Rev. David Jeremiah
Rev. John Piper
Rev. Robert Schuller

Let me know if you need more.

**Comment by yourcelf** [comment]
In version 0.3.1, the unabreviated "Reverend" also doesn't work correctly -- it's tagged as ``GivenName``.

    >>> probablepeople.tag("Reverend Martin Luther King, Jr.")

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/venv/local/lib/python2.7/site-packages/probablepeople/__init__.py", line 107, in tag
        raise RepeatedLabelError(raw_string, parse(raw_string), label)
    probablepeople.RepeatedLabelError: 

    ERROR: Unable to tag this string because more than one area of the string has the same label

    ORIGINAL STRING:  Reverend Martin Luther King, Jr.
    PARSED TOKENS:    [('Reverend', 'GivenName'), ('Martin', 'Surname'), ('Luther', 'GivenName'), ('King,', 'Surname'), ('Jr.', 'SuffixGenerational')]
    UNCERTAIN LABEL:  GivenName
