### ISSUE TITLE
Issue with Mc and Mac last names when separated with a space

### ISSUE THREAD

**Issue by Richard-West** [datamade/probablepeople#22]
Sometimes we encounter names such as:

Ronald Mac Donald
Ronald Mc Donald

Where the proper last name should be "MacDonald" and "McDonald".

The parser is unable to parse either name when the space is present.

**Comment by cathydeng** [comment]
cool, thanks for reporting. do you have some examples of this in real world data, so that we can re-train the model?

**Comment by Richard-West** [comment]
Hi, here are a few real world examples for both cases. If there is anything specific that you are looking for please let me know and I can preform some additional queries on some of our data files.

Mr. Brian Mac Kenzie                              
Mr. Mac Isaac       <-- Included because in this case Mac is the Given name                              
Ms. Alice Mac Leod                               
Mr. Mac P Shain      <-- Included because in this case Mac is the Given name                             
Kurt and Linda Mac Donald                        
Mr. Kevin T. Mac Lean                           
Mr. Jack Mac Kinnon                             
Ms. Gloria Mac Farlane                              
Ms. Cindy Mac Kendrick                          
Mr. Lawrence F. Mac Donald and Emma MacDonald  
Mr. Eli Mac Cluskey                             
Mr. Bobby Mac Kay                              
Mr. and Mrs. Richard Mac Pherson           


Mr. Matt Mc Gee                                   
Ms. Pat Mc Carty                             
Ms. Carla Mc Knight                             
Ms. Diana Mc Farlane                             
Mrs. Dee Mc Cullough                          
Ms. Patricia Mc Keny                                 
John H. Mc Waters                                
Mr. Gary Mc Rae                                   
Ms. Robin Mc Mullen                             
Mr. Fred V. Mc Bride, Jr.

**Comment by Richard-West** [comment]
I would be happy to issue a pull request with this data in the training file if you could let me know which file this data would go into. I think this would go into the probablepeople/name_data/labeled/labeled.xml file.

**Comment by fgregg** [comment]
Yup! That'd be great.

**Comment by Richard-West** [comment]
Just confirming, these names should be added to the labeled.xml file. 

You are not using any type of build scripts to convert the unlabeled files into the labeled.xml file, correct?

**Comment by fgregg** [comment]
The labeled names should be added to the labeled.xml file.

On Tue, Jan 5, 2016 at 11:41 AM, Richard West <notifications@github.com>
wrote:

> Just confirming, these names should be added to the labeled.xml file.
>
> You are not using any type of build scripts to convert the unlabeled files
> into the labeled.xml file, correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/probablepeople/issues/22#issuecomment-169076977>
> .
>



-- 
773.888.2718

**Comment by cathydeng** [comment]
@Richard-West sweet! you can use parserator to label strings at the command line, and it'll format training data properly. we only need a few (probably < 10) examples in labeled.xml for the model to learn about the pattern. also, when you're done, can you move some of these examples to the tests in https://github.com/datamade/probablepeople/blob/master/tests/test_data_labeled.xml?
