### ISSUE TITLE
feature request: allow override of person/corporation inference

### ISSUE THREAD

**Issue by mattkiefer** [datamade/probablepeople#25]
It would be nice if I could explicitly tell the parser whether a name is a person or corporation. i.e.:
probablepeople.tag('matt kiefer',person=True)

The reason being I'm running into issues with this pretty straightforward person name getting ID'd as a corporation:
probablepeople.tag('VERA, ELIZABETH')
(OrderedDict([('CorporationName', 'VERA, ELIZABETH')]), 'Corporation')

**Comment by fgregg** [comment]
I think this would be pretty good thing to do.

**Comment by jernsthausen** [comment]
Finding myself in concurrence on a current task.
