### ISSUE TITLE
optimizations for large data sets?

### ISSUE THREAD

**Issue by rkiddy** [datamade/probablepeople#26]
I am curious, have you all thought about ways to optimize the parsing for large data sets. I can call the parse() method, but that seems to be the only entry point.

I am pulling names out of a database, getting the pp splits and storing them in another table. I am pulling the data out of the table in chucks of 10,000. It has been running for a bit less than a week. I have over 6m name strings. My database access is not very optimized.

Just curious if you have suggestions.

**Comment by fgregg** [comment]
@rkiddy The only thing I can recommend is the general recommendations for profiling with python. http://stackoverflow.com/a/7693928/98080

If you can't find any significant speed improvements, this sounds like a task that would be easy to parallelize if you have multiple cpus.

**Comment by rkiddy** [comment]
The issue turned out to be my database access, by a couple of orders of magnitude. Should finish soon-ish now.
