### ISSUE TITLE
module 'probablepeople' has not attribute 'TAGGER'

### ISSUE THREAD

**Issue by caninapriori** [datamade/probablepeople#32]
I'm trying to label examples with the following command

`parserator label name_data/unlabeled/professors.csv name_data/labeled/profs.xml probablepeople`

Which gives me the following error:

`/home/*****/builds/probablepeople/probablepeople/__init__.py:66: UserWarning: You must train the model (parserator train [traindata] [modulename]) to create the company_learned_settings.crfsuite file before you can use the parse and tag methods`

  `warnings.warn('You must train the model (parserator train [traindata] [modulename]) to create the %s file before you can use the parse and tag methods' % MODEL_FILES[model_type])`

`/home/*****/builds/probablepeople/probablepeople/__init__.py:66: UserWarning: You must train the model (parserator train [traindata] [modulename]) to create the person_learned_settings.crfsuite file before you can use the parse and tag methods`

  `warnings.warn('You must train the model (parserator train [traindata] [modulename]) to create the %s file before you can use the parse and tag methods' % MODEL_FILES[model_type])`

`Traceback (most recent call last):`
  `File "/home/*****/PyEnvs/BaseLab/bin/parserator", line 11, in <module>
    sys.exit(dispatch())`
  `File "/home/*****/PyEnvs/BaseLab/lib/python3.5/site-packages/parserator/main.py", line 54, in dispatch
    args.func(args)`
  `File "/home/*****/PyEnvs/BaseLab/lib/python3.5/site-packages/parserator/main.py", line 75, in label
    manual_labeling.label(module, infile_path, outfile_path)`
  `File "/home/*****/PyEnvs/BaseLab/lib/python3.5/site-packages/parserator/manual_labeling.py", line 211, in label`
    `if module.TAGGER:`

`AttributeError: module 'probablepeople' has no attribute 'TAGGER'`

I have already trained the person and the company file using the code provided in the README, as well.

I'm using ProbablePeople as pulled from the repo

and

Parserator == 0.6.0

I've tried with Python 3.5.2 Python 2.7.12| I also tried downgrading Parserator to 0.4.1; no luck.

Any help would be super appreciated. Thank you!

**Comment by caninapriori** [comment]
Maybe a second issue, `python setup.py develop' is requiring sudo when I'm in a virtualenv??

**Comment by cathydeng** [comment]
ah, this is a bug that was introduced w/ some recent changes to probablepeople, thanks for reporting. if you use probablepeople at [this commit](https://github.com/datamade/probablepeople/commit/745bc4522a9e35ad7e0b272549c4f14330df6501), it should work.

**Comment by caninapriori** [comment]
And about the `AttributeError: module 'probablepeople' has no attribute 'TAGGER'` - I'm still getting that error?
