### ISSUE TITLE
script terminates with bad input string

### ISSUE THREAD

**Issue by merrymccarron** [datamade/probablepeople#34]
I passed in a bad string that was formatted like "Firstname Lastname, Company Owned By Person."

It terminates the process. I work with lots of mediocre data, and would rather not have to wrap everything in a try/except/else statement whenever I use your library. Change from an exception to a warning please.

Here's the error message:

    RepeatedLabelError: 
    ERROR: Unable to tag this string because more than one area of the string has the same label
    
    [[[my bad string and the way that probablepeople tried to parse it goes here-- this is very helpful]]]
    
    UNCERTAIN LABEL:  GivenName
    When this error is raised, it's likely that either (1) the string is not a valid person/corporation name or (2) some tokens were labeled incorrectly

**Comment by fgregg** [comment]
Hi @merrymccarron,

I'm sorry that that the current behavior is not convenient for you. Unfortunately, changing it would break a lot of existing code.

One way that you could get your desired behavior is to write a wrapper function that is something like.

```python
def wrapper(string):
    try:
        return usaddress.tag(string)
     except RepeatedLabelError:
        warnings.warn('repeated label')
        return string
```
