### ISSUE TITLE
Unable to locate package probablepeople

### ISSUE THREAD

**Issue by poornagurram** [datamade/probablepeople#40]
Error Screenshot :
<img width="1219" alt="screen shot 2017-04-13 at 6 59 44 pm" src="https://cloud.githubusercontent.com/assets/9065157/25006677/822e642a-207b-11e7-887f-3086ee87f098.png">

Directory Screenshot:
<img width="1273" alt="screen shot 2017-04-13 at 7 01 30 pm" src="https://cloud.githubusercontent.com/assets/9065157/25006736/b286bb22-207b-11e7-8f41-a9f1de2ece57.png">
Help me With this issue.

**Comment by jeancochrane** [comment]
Hey @poornagurram,

Sorry for the extra late reply! Are you still having trouble importing the package? If so, it'd help to see the commands you used to build `probablepeople`.

**Comment by poornagurram** [comment]
I waited for the reply and started using another library. Anyway Thanks.

**Comment by jeancochrane** [comment]
Sorry about that! Feel free to open a new issue if you decide to use probablepeople again.
