### ISSUE TITLE
one certain name crashes bulk parsing service

### ISSUE THREAD

**Issue by az0** [datamade/probablepeople#51]
The [bulk parsing service for probablepeople](https://parserator.datamade.us/probablepeople/bulk/) returns the following error 
````
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
````
If the input includes this line: `Solus Christi Brothers`

**Comment by fgregg** [comment]
Weird! @jeancochrane can you take a look at this when you get a chance?

**Comment by jeancochrane** [comment]
Two issues at play here:

1. That string throws a `RepeatedLabelError` (c.f. #57)
2. We weren't catching the error properly in the API

Opening up a PR in the API repo to fix 2. 1 has been superceded by #57.
