### ISSUE TITLE
Corporation names

### ISSUE THREAD

**Issue by fgregg** [datamade/probablepeople#6]
Let's see if we can extend this project to also handle company names.

Previous art 

- @arowla's https://github.com/sunlightlabs/name-cleaver
- @zmaril's https://github.com/sunlightlabs/echelon/blob/master/src/echelon/parser.bnf
- others?

**Comment by zmaril** [comment]
A warning from our (limited) experience with this work: it seems like folks who fill out forms are more likely to include extraneous and undocumented/informal information in fields for organization/corporate names than they are for fields about people's name. The formal parser routine is pretty good and straightforward for parsing cleanish corporate names. The difficulty we ran into was understanding things like "Corp A on behalf of Corp B" or "Corp A formerly known as Corp B". Although only a fourth of the file you linked deals with embedded relationships, the vast amount of work I put in on the parser as a whole was dealing with how to represent and deal with the information from embedded relationships. We've only run this on one dataset, so who knows if the pattern holds though. I guess the main point is that in our experience the company names have been messier than people's name for parsing purposes.

**Comment by fgregg** [comment]
Thanks @zmaril. Do you have a gold-standard set of tagged corporation names
now?

**Comment by zmaril** [comment]
Nope. I have some unit tests for the parser but they are mostly edges that I ran into around embedded relationships.

**Comment by jernsthausen** [comment]
@fgregg @cathydeng could we use campaign data to build something that first decides what is a company name versus a name and then decides which parser to use on it? I'm thinking we could use data where someone has filled in their name and an employer as training data for the categorization.

**Comment by fgregg** [comment]
We could. Not sure what the best approach is. I suppose we should just
start training probable people with company names.

**Comment by jernsthausen** [comment]
Same. It seems like an important consideration involves how we'll store entities from data sets with different features. Do you have anything I could look at for what you're thinking is there?

**Comment by fgregg** [comment]
DONEZO!
